[package]
name = "chasm"
version = "0.1.0"
description = "game"
authors = ["oth"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
rand = "0.9.1"
